INSERT INTO `Quan_tri` VALUES (1,'Xuka','xuka','123456');
INSERT INTO `Quan_tri` VALUES (2,'Choky','choky','123456');

INSERT INTO `Loai_san_pham` VALUES (1,'Áo','Ao.png');
INSERT INTO `Loai_san_pham` VALUES (2,'Quần','Quan.png');
INSERT INTO `Loai_san_pham` VALUES (3,'Đầm','Dam.png');
INSERT INTO `Loai_san_pham` VALUES (4,'Jumpsuit','Jumpsuit.png');

INSERT INTO `San_pham` VALUES ('SP_1','Áo croptop hoạ tiết da beo',1,'Áo croptop cổ cao basic, chất liệu nhung in họa tiết da beo trendy thích hợp cho những cô nàng cá tính, năng động.','Nhung',350000,1);
INSERT INTO `San_pham` VALUES ('SP_2','Áo phi tay dài nhấn nơ cổ',1,'Kiểu dáng tay dài với độ rộng vừa phải. Phần cổ áo nhún nhẹ, phần chân cổ nối dài tạo thành dây buộc nơ bên trái cổ. Tay áo nhún nhẹ tạo độ phồng và viền nhỏ ở cổ tay','Lụa tuyết',355000,1);
INSERT INTO `San_pham` VALUES ('SP_3','Quần basic ống ôm fw18',2,'Quần basic ống ôm fw18','Kakil',455000,1);
INSERT INTO `San_pham` VALUES ('SP_4','Quần short lưng liền xếp ly 1 bên',2,'Quần short lưng liền xếp ly 1 bên','Kaki',295000,1);
INSERT INTO `San_pham` VALUES ('SP_5','Đầm phi lụa rút nhún thân dưới tay dài',3,'Đầm phi lụa rút nhún thân dưới tay dài','Phi bóng',685000,1);
INSERT INTO `San_pham` VALUES ('SP_6','Đầm dài in hoạ tiết strange nature nhấn ngực',3,'Đầm dài in hoạ tiết strange nature nhấn ngực','Silk',985000,1);
INSERT INTO `San_pham` VALUES ('SP_7','Jumpsuit đắp chéo cổ danton',4,'Jumsuit công sở lấy cảm hứng từ áo vest với điểm nhấn là chi tiết trang trí hai bên eo. Mẫu jumsuit short với họa tiết sọc thanh lịch, cá tính.','Bố sọc',595000,1);
INSERT INTO `San_pham` VALUES ('SP_8','Jumpsuit dài sơmi thắt lưng',4,'Jumpsuit dài sơmi thắt lưng','Thun',685000,1);
INSERT INTO `San_pham` VALUES ('SP_9','Áo tay dài kẹp bèo',1,'Áo kiểu tay dài với chi tiết bèo nhún ở cổ và trên đường raglan.','Silk',395000,1);
INSERT INTO `San_pham` VALUES ('SP_10','Áo phi bóng tay dài nhấn nút',1,'Áo satin đang là 1 item rất HOT không thể thiếu trong tủ đồ của bạn . Được thiết kế với phần rút nhẹ ở chân cổ sẽ giúp bạn thật sang trọng nhưng vẫn không kém phần tinh tế, phù hợp đi làm lẫn dạo phố ngày cuối năm.','Satin',463000,1);
INSERT INTO `San_pham` VALUES ('SP_11','Đầm sọc tay dài thắt dây đeo',3,'Đầm form suông cách điệu với chi tiết lai bất đối xứng. Điểm nhấn đặc biệt của đầm là dây lưng khoen D cá tính tôn lên vòng eo, thích hợp đi làm, đi chơi.','Lụa sọc',490000,1);
INSERT INTO `San_pham` VALUES ('SP_12','Jumsuit hộp túi nút to',4,'Jumpsuit short túi hộp đính nút','Kaki',357000,1);

INSERT INTO `San_pham_chi_tiet` VALUES (1,'SP_1','Trắng','S',10,0);
INSERT INTO `San_pham_chi_tiet` VALUES (2,'SP_1','Trắng','M',5,0);
INSERT INTO `San_pham_chi_tiet` VALUES (3,'SP_1','Trắng','L',3,0);
INSERT INTO `San_pham_chi_tiet` VALUES (4,'SP_1','Da','S',3,0);
INSERT INTO `San_pham_chi_tiet` VALUES (5,'SP_1','Da','M',4,0);
INSERT INTO `San_pham_chi_tiet` VALUES (6,'SP_1','Da','L',6,0);
INSERT INTO `San_pham_chi_tiet` VALUES (7,'SP_2','Hồng','S',2,0);
INSERT INTO `San_pham_chi_tiet` VALUES (8,'SP_2','Hồng','S',3,0);
INSERT INTO `San_pham_chi_tiet` VALUES (9,'SP_2','Hồng','L',5,0);
INSERT INTO `San_pham_chi_tiet` VALUES (10,'SP_2','Vàng','S',5,0);
INSERT INTO `San_pham_chi_tiet` VALUES (11,'SP_2','Vàng','M',14,0);
INSERT INTO `San_pham_chi_tiet` VALUES (12,'SP_2','Vàng','L',12,0);
INSERT INTO `San_pham_chi_tiet` VALUES (13,'SP_3','Nâu','S',14,0);
INSERT INTO `San_pham_chi_tiet` VALUES (14,'SP_3','Nâu','M',11,0);
INSERT INTO `San_pham_chi_tiet` VALUES (15,'SP_3','Đen','S',15,0);
INSERT INTO `San_pham_chi_tiet` VALUES (16,'SP_3','Đen','L',13,0);
INSERT INTO `San_pham_chi_tiet` VALUES (17,'SP_4','Nâu','S',4,0);
INSERT INTO `San_pham_chi_tiet` VALUES (18,'SP_4','Kem','M',6,0);
INSERT INTO `San_pham_chi_tiet` VALUES (19,'SP_5','Da','S',13,0);
INSERT INTO `San_pham_chi_tiet` VALUES (20,'SP_5','Cam','L',14,0);
INSERT INTO `San_pham_chi_tiet` VALUES (21,'SP_6','Kem','S',4,0);
INSERT INTO `San_pham_chi_tiet` VALUES (22,'SP_6','Kem','M',12,0);
INSERT INTO `San_pham_chi_tiet` VALUES (23,'SP_6','Kem','L',14,0);
INSERT INTO `San_pham_chi_tiet` VALUES (24,'SP_7','Đỏ','S',12,0);
INSERT INTO `San_pham_chi_tiet` VALUES (25,'SP_7','Đỏ','L',5,0);
INSERT INTO `San_pham_chi_tiet` VALUES (26,'SP_8','Cam','S',12,0);
INSERT INTO `San_pham_chi_tiet` VALUES (27,'SP_8','Cam','M',15,0);
INSERT INTO `San_pham_chi_tiet` VALUES (28,'SP_9','Trắng','S',13,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (29,'SP_9','Cam','L',12,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (30,'SP_10','Hồng','S',4,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (31,'SP_10','Hồng','M',5,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (32,'SP_10','Xanh lá','S',5,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (33,'SP_10','Xanh lá','M',12,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (34,'SP_10','Xanh lá','L',15,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (35,'SP_11','Đen','S',4,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (36,'SP_11','Đen','L',4,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (37,'SP_12','Xanh','S',45,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (38,'SP_12','Xanh','M',11,NULL);
INSERT INTO `San_pham_chi_tiet` VALUES (39,'SP_12','Xanh','L',21,NULL);

INSERT INTO `Hinh_san_pham` VALUES (1,'SP_1','SP1_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (2,'SP_1','SP1_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (3,'SP_1','SP1_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (4,'SP_1','SP1_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (7,'SP_2','SP2_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (8,'SP_2','SP2_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (9,'SP_2','SP2_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (10,'SP_2','SP2_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (11,'SP_3','SP3_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (12,'SP_3','SP3_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (13,'SP_3','SP3_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (14,'SP_3','SP3_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (15,'SP_4','SP4_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (16,'SP_4','SP4_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (17,'SP_4','SP4_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (18,'SP_4','SP4_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (19,'SP_5','SP5_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (20,'SP_5','SP5_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (21,'SP_5','SP5_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (22,'SP_5','SP5_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (23,'SP_6','SP6_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (24,'SP_6','SP6_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (25,'SP_6','SP6_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (26,'SP_7','SP7_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (27,'SP_7','SP7_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (28,'SP_7','SP7_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (29,'SP_7','SP7_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (30,'SP_8','SP8_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (31,'SP_8','SP8_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (32,'SP_8','SP8_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (33,'SP_9','SP9_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (34,'SP_9','SP9_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (35,'SP_9','SP9_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (36,'SP_9',' SP9_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (37,'SP_10','SP10_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (38,'SP_10','SP10_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (39,'SP_10','SP10_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (40,'SP_10','SP10_4.jpg');
INSERT INTO `Hinh_san_pham` VALUES (41,'SP_11','SP11_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (42,'SP_11','SP11_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (43,'SP_11','SP11_3.jpg');
INSERT INTO `Hinh_san_pham` VALUES (44,'SP_12','SP12_1.jpg');
INSERT INTO `Hinh_san_pham` VALUES (45,'SP_12','SP12_2.jpg');
INSERT INTO `Hinh_san_pham` VALUES (46,'SP_12','SP12_3.jpg');

INSERT INTO `Cua_hang` VALUES (1,'Nguyễn Thị Thập','379 Nguyễn Thị Thập, P.Tân Phong, Quận 7, Hồ Chí Minh','028.6298.9987');
INSERT INTO `Cua_hang` VALUES (2,'Quang Trung','183 Quang Trung, P.10, Quận Gò Vấp','028.2217.8411');
INSERT INTO `Cua_hang` VALUES (3,'Lê Văn Việt','79 Lê Văn Việt, P.Hiệp Phú, Quận 9, Hồ Chí Minh','028.6287.4688');

